CREATE TABLE dbo.ItemImage
(
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY
  ,ItemId UNIQUEIDENTIFIER NOT NULL
  ,DateCreated DATETIME NOT NULL
  ,CONSTRAINT FK_Item_Id FOREIGN KEY (ItemId) REFERENCES dbo.Item(Id)
);